# Generated by Django 5.2 on 2025-05-03 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('weight', models.PositiveIntegerField(help_text='Weight in grams')),
                ('available', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, default='menu_images/default.jpg', null=True, upload_to='menu_images/')),
                ('category', models.CharField(choices=[('cold', 'Cold Dishes'), ('hot', 'Hot Dishes'), ('dessert', 'Desserts'), ('drink', 'Drinks')], default='cold', max_length=20)),
            ],
        ),
    ]
